services:
  # PocketBase Database
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
      args:
        - PB_VERSION=0.22.17  # Fixed: add this line
    ports:
      - '8090:8090'
    volumes:
      - pocketbase_data:/pb_data
    environment:
      - PB_ENCRYPTION_SECRET=${PB_ENCRYPTION_SECRET:-change-me-in-production}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # SvelteKit Application
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PUBLIC_POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      pocketbase:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pocketbase_data: