version: '3.8'

services:
  # PocketBase Database
  pocketbase:
    image: mootech/pocketbase:latest
    ports:
      - '8090:8090'
    volumes:
      - pocketbase_data:/pb_data
      - ./pb_migrations:/pb_migrations # optional: for initial data
    environment:
      - PB_ENCRYPTION_SECRET=${PB_ENCRYPTION_SECRET:-change-me-in-production}
    healthcheck:
      test:
        ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8090/api/health']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # SvelteKit Application
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PUBLIC_POCKETBASE_URL="http://localhost:8090"
    depends_on:
      pocketbase:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/build
    restart: unless-stopped

volumes:
  pocketbase_data:
